### ISSUE TITLE
New world order -- restructure cityIO, GD, data etc

### ISSUE THREAD

**Issue by RELNO** [RELNO/CSharpScope_TemplateProject#32]
As mentioned, the goal is for standalone, clear fragments:
1. cityIO to be restructured as DATA and VIZ comp. 
2. DATA controls all data elements: Send, receive from scanners, from cityIO and parse 
3. VIZ does 3d representation, heatmaps + analysis but not prj. mapping
4. Prj. mapping as standalone as well
5. UI to control each of these separately - so multiple UIs

**Comment by foldalma** [comment]
WIP on newworldorder branch--you can try deleting GridDecoder & al now.

**Comment by foldalma** [comment]
i might make a new issue for the UI
