### ISSUE TITLE
Fix multiple keystone object saving (keystone settings for the projected & viewed quads)

### ISSUE THREAD

**Issue by foldalma** [RELNO/CSharpScope_TemplateProject#6]

**Comment by RELNO** [comment]
Also, let's try and set them in a clear folder [/projectSetting or something] with some commenting at the top of each JSON to explain purpose

**Comment by foldalma** [comment]
Sounds good! I can work on all the JSON setting saving today.

**Comment by RELNO** [comment]
Cool, add this to save list:
Fix / save to file scanners grid location offset so that scanning could resume on play

**Comment by foldalma** [comment]
The latter is done!
