### ISSUE TITLE
Add image processing features to keystone shader (blur, brightness, contrast) 

### ISSUE THREAD

**Issue by RELNO** [RELNO/CSharpScope_TemplateProject#8]
Blur can help reduce color variations between scanner Ray and given pixel
--

**Comment by RELNO** [comment]
Blur can help reduce color variations between scanner Ray and given pixel

**Comment by RELNO** [comment]
![image](https://user-images.githubusercontent.com/14296774/28082088-6c0a4e98-663f-11e7-8b4d-83dad816e47c.png)

**Comment by foldalma** [comment]
^ is this a corrected image?

**Comment by RELNO** [comment]
Just a quick Photoshop (brightness, contrast, blur) so you can test against
previous image and see if helpful.

**Comment by foldalma** [comment]
before:
![screenshot 2017-07-11 16 56 49](https://user-images.githubusercontent.com/5706296/28090786-83e3997c-665b-11e7-9e94-3a1cf51930ac.png)

after:
![screenshot 2017-07-11 16 56 30](https://user-images.githubusercontent.com/5706296/28090796-87905aec-665b-11e7-8554-f3c32d4df7ff.png)

we can test it and see if it helps.

**Comment by RELNO** [comment]
From the look of it it seems to improve errors, but I think (hope) that
blur would also have runtime effect as video pixels would change their
color less dramatically. Maybe there are also other ways to achieve this.

On Jul 11, 2017 17:08, "Dalma Foldesi" <notifications@github.com> wrote:

before:
[image: screenshot 2017-07-11 16 56 49]
<https://user-images.githubusercontent.com/5706296/28090786-83e3997c-665b-11e7-9e94-3a1cf51930ac.png>

after:
[image: screenshot 2017-07-11 16 56 30]
<https://user-images.githubusercontent.com/5706296/28090796-87905aec-665b-11e7-8554-f3c32d4df7ff.png>

we can test it and see if it helps.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RELNO/CSharpScope_TemplateProject/issues/8#issuecomment-314572561>,
or mute the thread

**Comment by foldalma** [comment]
closing this and will test blur filters in a separate issue!
